[package]
name = "mote-api"
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
description = "Message and API definitions for communicating with Mote"
license = "MIT"
repository = "https://github.com/empriselab/mote"
documentation = "https://docs.rs/mote-api"
keywords = ["robotics", "embedded", "protocol", "serialization"]
categories = ["embedded", "no-std", "network-programming"]

[lints.clippy]
all = { level = "warn", priority = -1 }

[dependencies]
postcard = { version = "1", default-features = false, features = ["alloc"] }
defmt = { version = "1.0", features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = [
    "derive",
    "alloc",
] }
corncobs = "0.1"
thiserror = { version = "2.0", default-features = false }
libm = "0.2"

schemars = { version = "1.2", optional = true }
units = { package = "sci-units", version = "0.6", features = ["use_defmt", "f32"] }
heapless = { version = "0.9", features = ["defmt", "serde"] }


[features]
schemars = ["dep:schemars"]

[dev-dependencies]
async-std = "1"
color_space = "0.5"
futures-util = "0.3"
mdns = "3.0"
rerun = { version = "0.30", features = ["web_viewer"] }
anyhow = "1.0"
